
  before_script:
  - IMAGE_TAG="$(echo $CI_COMMIT_SHA | head -c 8)"

  cache:
    paths:
      - maven.repository/

  variables:
    MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=maven.repository/"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
    REPOSITORY_URL: 593646001153.dkr.ecr.eu-west-2.amazonaws.com/mwf

  stages:
    - unit-test
    - package
    - deploy

  maven-unit-test:
    image: maven:3-jdk-8
    stage: unit-test
    script:
      - cd api-gateway
      - mvn $MAVEN_CLI_OPTS clean package -P unit-test
      - mkdir target/dependency
      - (cd target/dependency; jar -xf ../*exec.jar)
    artifacts:
      reports:
        junit: api-gateway/target/surefire-reports/TEST-*.xml

  build-image:
    image: docker:latest
    stage: package
    services:
      - name: docker:dind
    script:
      - apk add --no-cache curl jq python3 py-pip
      - pip install awscli
      - $(aws ecr get-login --no-include-email --region eu-west-2)
      - cd api-gateway
      - docker build -t $REPOSITORY_URL:latest .
      - docker tag $REPOSITORY_URL:latest $REPOSITORY_URL:$IMAGE_TAG
      - docker push $REPOSITORY_URL:latest
      - docker push $REPOSITORY_URL:$IMAGE_TAG


  deploy:
    image: python:latest
    stage: deploy
    script:
      - pip install awscli
      - echo $REPOSITORY_URL:$IMAGE_TAG
      - cd api-gateway
      - aws ecs register-task-definition --region eu-west-2 --family mwf --cli-input-json file://aws/ecs-task-definition.json
      - aws ecs update-service --region eu-west-2 --cluster mwf-ci --service api-gateway  --task-definition mwf-api-gateway
